In [1]:
from opt_einsum import contract # idk why but its required to avoid bug in contract with numpy arrays
import torch
import numpy as np
from tqdm.auto import tqdm
torch.set_default_tensor_type(torch.cuda.DoubleTensor)
device=torch.device('cuda:0')
torch.cuda.set_device(device)


In [2]:
from TNModels import AKLT3D
# import importlib;import HOTRG;importlib.reload(HOTRG)
from HOTRG import HOTRG_layers,forward_observalbe_tensor_moments,trace_tensor,trace_two_tensors,forward_observable_tensor

In [4]:
params=AKLT3D.get_default_params()
# +.008
params['a1']=2
print(params['a1'])
T0=AKLT3D(params).get_T0()
layers,Ts,logTotals=HOTRG_layers(T0,max_dim=10,nLayers=15,options={'mcf_enabled':True,'gilt_enabled':False,'mcf_fix_unitary_enabled':True})
_=[trace_two_tensors(T).item() for T in Ts]
print(_)


Y0,checkerboard=AKLT3D(params).get_observable('magnetizationZ')
_,T_ops,_=forward_observable_tensor(T0,Y0,layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(T_op).item(),trace_two_tensors(T).item()) for T_op,T in zip(T_ops,Ts)]
print([(_[0]/_[1] if _[1]!=0 else 0) for _ in _])


Y0,checkerboard=AKLT3D(params).get_observable('magnetizationX')
checkerboard=True
_,T_ops,_=forward_observable_tensor(T0,Y0,layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(T_op).item(),trace_two_tensors(T).item()) for T_op,T in zip(T_ops,Ts)]
print([(_[0]/_[1] if _[1]!=0 else 0) for _ in _])

Y0,checkerboard=AKLT3D(params).get_observable('magnetizationY')
checkerboard=True
_,T_ops,_=forward_observable_tensor(T0,Y0,layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(T_op).item(),trace_two_tensors(T).item()) for T_op,T in zip(T_ops,Ts)]
print([(_[0]/_[1] if _[1]!=0 else 0) for _ in _])



2
Generating HOTRG layers


  0%|          | 0/15 [00:00<?, ?it/s]

HOTRG layers generated
[1.1757127162748148e-31, 0.003610471979310956, 9177.467559955967, 9015.089967074526, 0.006027815758769782, 0.0032364906452120017, 0.0033724479060480016, 0.0023514035157004916, 0.0012957484072635022, 0.0010322470431337132, 0.0011740796330449617, 0.003070562547837459, 0.023475210475967442, 0.10839803533357828, 0.11654556625855127, 0.1218154809553]


0it [00:00, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

[0.0, -1.724216931841406, -9.480236461198036e-32, 3.5627678282342966e-32, 1.8775530460283522e-32, 1.8683243167003216e-32, 1.7972883148941855e-32, 1.656579171906588e-32, 1.4999154597108604e-32, 1.2037949775223091e-32, 7.538331517850672e-33, 1.9942611793489207e-33, 2.0830802820524406e-35, 7.263421987775642e-36, 3.308153742650005e-36, 1.8744316382022968e-36]


0it [00:00, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

[-115.4351243732837, -2.007612135423252, -3.025316047434027, 2.890064509722311, 2.9692150454972603, 2.9513549407734883, 2.805853053432228, 2.6729959805531904, 2.4231611964242483, 1.9509062773469539, 1.2222735013306238, 0.3195608065475881, 0.0032699581621740254, 0.0012576984592748248, 0.00040972887348310447, 0.00011747558698788714]


0it [00:00, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

[115.43512437328374, 2.0076121354232463, 3.0821448347256344, -3.0207758538330434, -2.993396445436277, -2.988411595971841, -2.9336747441703532, -3.0063600709943556, -3.16660985500066, -3.6126862668619917, -4.347286401084834, -5.285368576869955, -5.6023299803168065, -5.603249339957013, -5.603604327733268, -5.603636953023033]


In [ ]:


# params=AKLT3D.get_default_params()
# params['a1']+=.008
# print(params['a1'])
# T0=AKLT3D(params).get_T0()
# layers,Ts,logTotals=HOTRG_layers(T0,max_dim=10,nLayers=15,options={'mcf_enabled':True,'gilt_enabled':False,'mcf_fix_unitary_enabled':True})
# _=[trace_two_tensors(T).item() for T in Ts]
# print(_)


In [3]:
import importlib;import transfer_matrix;importlib.reload(transfer_matrix)
from transfer_matrix import get_scdims,get_transfer_matrix_operator
# 

In [ ]:
from TNModels import AKLT3D
import importlib;import HOTRG;importlib.reload(HOTRG)
from HOTRG import HOTRG_layers,forward_observalbe_tensor_moments,trace_tensor,trace_two_tensors

params=AKLT3D.get_default_params()
params['a1']+=.008
params['a1']
T0=AKLT3D(params).get_T0()
layers,Ts,logTotals=HOTRG_layers(T0,max_dim=10,nLayers=15,options={'mcf_enabled':False,'gilt_enabled':False,'mcf_fix_unitary_enabled':False})
Y0,checkerboard=AKLT3D(params).get_observable('magnetizationZ')
T_op_momentss,logTotals=forward_observalbe_tensor_moments([T0,Y0],layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(Y).item(),trace_two_tensors(T).item()) for T,Y in T_op_momentss[:]]
[((_[0]/_[1] if _[1]!=0 else 0),_[1]) for _ in _]

In [4]:
scdimss=[get_scdims(T,n=(1,1),k=5)[0] for T in Ts[::3]]
scdimss

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

[tensor([0.0000, 0.1497]),
 tensor([0.0000, 0.1050, 0.1050, 0.1331, 0.2980]),
 tensor([0.0000, 0.0371, 0.0371, 0.0632, 0.1074]),
 tensor([0.0000, 0.0027, 0.0165, 0.0165, 0.0181]),
 tensor([0.0000, 0.0116, 0.0136, 0.0136, 0.0136]),
 tensor([0.0000, 0.0024, 0.0024, 0.0025, 0.0025])]

tensor([0.0000, 0.1497])